---
header-includes: \usepackage{color}
output:
  pdf_document:
    fig_caption: no
  html_document: default
---

```{r, echo=FALSE, warning=FALSE, message=FALSE}
whichcomp <- strsplit(getwd(),"/")[[1]][3]
load(paste0("c:/users/", whichcomp, "/Dropbox/Resma3/Resma3.RData"))
require(knitr)
require(ggplot2)
require(grid)
```
`r hl()$basefontsize()`


##ESMA 3102 - Introduction to Statistics II

###

[Resma3.RData](http://academic.uprm.edu/wrolke/Resma3/Resma3.RData?Ver 2.7) (Ver 2.7)


All these pages are also available as html [here](index.html).  

For a nice introduction to Statistics watch the PBS-NOVA episode [Prediction by the Numbers](http://www.pbs.org/video/prediction-by-the-numbers-hg2znc/) 

###1 General Information   

1.1. [Syllabus](syl.pdf)  

###2 Computer and R

2.1. [Introduction to Using the Computer and to R](../Resma3/computerandR.pdf)  

2.2. [Short List of Important R commands](../Resma3/short.list.commands.html)

2.3. [R routines](../Resma3/routines.pdf)

###3 Some Basic Ideas and Concepts

3.1. [Introduction to ESMA 3102](intro.pdf) 

3.2. [Graphs](graphs.pdf) 

3.3. [Outliers](outlier.pdf) 

3.4. [Describing a Population: Probability Distributions](pop.pdf) 

3.5 [Confidence Intervals](estimation.pdf) 

3.6 [Hypothesis Testing - Concept](ht-intro.pdf) 

3.7 [Hypothesis Testing](hyptest.pdf) 

3.8 [The Lady Tasting Tea](lady-tea.pdf)

3.9 [Methods for one Variable](onesample.pdf) 

3.10 [Bayesian Statistics](bayes.pdf)

3.11 [Exercises](exercise1.pdf)

###4 Is there a relationship?

| Method  | Predictor | Response |
|---|---|---|
| 4.1 [Categorical Data Analysis](cat.pdf) | Categorical | Categorical |
| 4.2 [ANOVA](oneway.pdf) | Categorical | Quantitative |
| 4.3 [Correlation](cor.pdf) | Quantitative | Quantitative |

4.4 [Correlation vs Causation](correlation-causation.pdf)

4.5 [Non-Normal Residuals, No Equal Variance - Transformation](trans.pdf)

4.6[Non-Normal Residuals, No Equal Variance - Non-Parametric](nonpar.pdf)

4.7 [Exercises](exercise2.pdf)

###5 If so, what is there a relationship?

| Method  | Predictor | Response |
| ----- | -----| ----- |
| 5.1 [ANOVA - Multiple Comparison](oneway1.pdf) | Categorical | Quantitative | 
| 5.2 [Simple Regression](slr.pdf) | Quantitative | Quantitative | 

5.3 [Assumptions of SLR](assumptions.pdf)

5.4 [Hypothesis Tests in SLR](tests.pdf) 	 		 

5.5 [Prediction](predict.pdf)   	 		 

5.6 [Non-Normal Residuals, No Equal Variance](fix.pdf)  

5.7 [Non-Linear Models: Transformations and Polynomials](nonlin.pdf) 	 		 

5.8 [Coefficient of Determination and Over-fitting](overfit.pdf) 	 		 


4.9 [Exercises](exercise3.pdf)
 
###6 More Than One Predictor

| Method  | Predictors | Response |
| ----- | -----| ----- |
| 6.1 [Categorical Data - Simpson's Paradox](simpson.pdf) | All Categorical | Categorical |
| 6.2 [ANOVA](twoway.pdf) | All Categorical | Quantitative | 
| 6.3 [Mulitple Regression](multreg.pdf) | Quantitative | Quantitative |
| 6.4 [Regression with Dummy Variables](dummy.pdf) | Quantitative/Categorical | Quantitative |

6.5 [Exercises](exercise4.pdf)
