---
header-includes: \usepackage{color}
output:
  html_document: default
  pdf_document:
    fig_caption: no
---

```{r, echo=FALSE, warning=FALSE, message=FALSE}
whichcomp <- strsplit(getwd(),"/")[[1]][3]
load(paste0("c:/users/", whichcomp, "/Dropbox/Resma3/Resma3.RData"))
require(knitr)
require(ggplot2)
require(grid)
```
`r hl()$basefontsize()`

##ESMA 3102 - Introduction to Statistics II

[Resma3.RData](http://academic.uprm.edu/wrolke/Resma3/Resma3.RData?Ver 2.8) (Ver 2.8)

All these pages are also available as pdfs [here](index_pdf.pdf).  

For a nice introduction to Statistics watch the PBS-NOVA episode [Prediction by the Numbers](http://www.pbs.org/video/prediction-by-the-numbers-hg2znc/)  

###1 General Information   

1.1.  [Syllabus](syl.html)  

###2 Computer and R

2.1.  [Introduction to Using the Computer and to R](../Resma3/computerandR.html)  

2.2.  [Short List of Important R commands](../Resma3/short.list.commands.html)

2.3.  [R routines](../Resma3/routines.html)

2.4.  [Resma3 vs base R](../Resma3/baseR.html)

###3 Some Basic Ideas and Concepts

3.1.  [Introduction to ESMA 3102](intro.html) 

3.2.  [Graphs](graphs.html) 

3.3.  [Outliers](outlier.html) 

3.4.  [Describing a Population: Probability Distributions](pop.html) 

3.5.  [Confidence Intervals](estimation.html) 

3.6.  [Hypothesis Testing - Concept](ht-intro.html) 

3.7.  [Hypothesis Testing](hyptest.html) 

3.8.  [The Lady Tasting Tea](../esma joint/lady-tea.html) 

3.9.  [Methods for one Variable](onesample.html) 

3.10. [Bayesian Statistics](bayes.html)

3.11. [Exercises](exercise1.html)

###4 Is there a relationship?

| Method  | Predictor | Response |
|---|---|---|
| 4.1.  [Categorical Data Analysis](cat.html) | Categorical | Categorical |
| 4.2.  [ANOVA](oneway.html) | Categorical | Quantitative |
| 4.3.  [Correlation](cor.html) | Quantitative | Quantitative |

4.4.  [Correlation vs Causation](correlation-causation.html)

4.5.  [Non-Normal Residuals, No Equal Variance - Transformation](trans.html)

4.6.  [Non-Normal Residuals, No Equal Variance - Non-Parametric](nonpar.html)

4.7.  [Exercises](exercise2.html)

###5 If so, what is there a relationship?

| Method  | Predictor | Response |
| ----- | -----| ----- |
| 5.1.  [ANOVA - Multiple Comparison](oneway1.html) | Categorical | Quantitative | 
| 5.2.  [Simple Regression](slr.html) | Quantitative | Quantitative | 

5.3.  [Assumptions of SLR](assumptions.html)

5.4.  [Hypothesis Tests in SLR](tests.html) 	 		 

5.5.  [Prediction](predict.html)   	 		 

5.6.  [Non-Normal Residuals, No Equal Variance](fix.html)  

5.7.  [Non-Linear Models: Transformations and Polynomials](nonlin.html) 	 		 

5.8.  [Coefficient of Determination and Over-fitting](overfit.html) 	

5.9.  [Exercises](exercise3.html)
 
###6 More Than One Predictor

| Method  | Predictors | Response |
| ----- | -----| ----- |
| 6.1.  [Categorical Data - Simpson's Paradox](simpson.html) | All Categorical | Categorical |
| 6.2.  [ANOVA](twoway.html) | All Categorical | Quantitative | 
| 6.3.  [Mulitple Regression](multreg.html) | Quantitative | Quantitative |
| 6.4.  [Regression with Dummy Variables](dummy.html) | Quantitative/Categorical | Quantitative |

6.5.  [Exercises](exercise4.html)
